steps:
  - name: asia.gcr.io/hexavator/friendease-backend
    args:
      - "build"
      - "-t"
      - "asia.gcr.io/hexavator/friendease-backend:$COMMIT_SHA"
      - "."
  - name: asia.gcr.io/hexavator/friendease-backend
    args:
      - "push"
      - "asia.gcr.io/hexavator/friendease-backend:$COMMIT_SHA"
  - name: "asia.gcr.io/cloud-builders/gcloud"
    args:
      - "run"
      - "deploy"
      - "friendease-backend"
      - "--image=asia.gcr.io/hexavator/friendease-backend:$COMMIT_SHA"
      - "--region=us-central1"
      - "--cpu=2"
      - "--memory=2048Mi"
      - "--allow-unauthenticated"
images:
  - "asia.gcr.io/hexavator/friendease-backend:$COMMIT_SHA"
